# Generated by Django 4.2.19 on 2025-03-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_text', models.TextField()),
                ('encrypted_text', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
