# Generated by Django 4.2.19 on 2025-03-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watcho', '0003_encryptiondecryptionlog_delete_dummymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encryption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_text', models.TextField()),
                ('encrypted_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EncryptionDecryptionLog',
        ),
    ]
