# Generated by Django 4.2.19 on 2025-02-27 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deactivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255)),
                ('end_date', models.DateField()),
                ('device_id', models.CharField(max_length=255)),
                ('deactivated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='deactivated', max_length=255)),
                ('deactivated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
