# Generated by Django 4.2.19 on 2025-02-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_paymentlog_amount_paymentlog_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='final_status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='varified_resonse',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
