# Generated by Django 4.2.19 on 2025-02-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0003_paymentlog_final_status_paymentlog_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='paymentlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='client_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='final_status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='order_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
