# Generated by Django 4.2.19 on 2025-03-17 09:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ott_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])])),
            ],
        ),
        migrations.CreateModel(
            name='OTTAggregator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
            ],
            options={
                'verbose_name': 'OTT Aggregator',
                'verbose_name_plural': 'OTT Aggregators',
            },
        ),
        migrations.CreateModel(
            name='OTTPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('otts', models.ManyToManyField(related_name='ott_plans_associated', to='ott_subscription.ott')),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ott_subscription.ottaggregator')),
            ],
        ),
        migrations.CreateModel(
            name='SkylinkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('ott_plans', models.ManyToManyField(to='ott_subscription.ottplan')),
            ],
        ),
        migrations.CreateModel(
            name='OTTSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('plan_id', models.CharField(max_length=255)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ott_subscription.ottaggregator')),
            ],
        ),
        migrations.CreateModel(
            name='OTTActivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('plan_id', models.CharField(max_length=255)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
                ('input', models.JSONField(blank=True, null=True)),
                ('response_status', models.IntegerField(blank=True, null=True)),
                ('output', models.JSONField(blank=True, null=True)),
                ('endpoint', models.CharField(blank=True, max_length=5000, null=True)),
                ('platform_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ott_subscription.ottaggregator')),
            ],
        ),
        migrations.AddField(
            model_name='ott',
            name='ott_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ott_plans', to='ott_subscription.ottplan'),
        ),
    ]
