# Generated by Django 4.2.19 on 2025-03-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTTPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('watcho', 'Watcho'), ('play_box', 'Play Box'), ('hotstar', 'Hotstar'), ('ottplay', 'OTTplay'), ('tata_play_binge', 'Tata Play Binge')], max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20)),
            ],
        ),
    ]
