# Generated by Django 4.2.19 on 2025-03-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ottplan',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='SkylinkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('ott_plans', models.ManyToManyField(to='ott_subscription.ottplan')),
            ],
        ),
    ]
