# Generated by Django 4.2.19 on 2025-03-17 12:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott_subscription', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ottplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
