# Generated by Django 4.2.19 on 2025-03-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott_subscription', '0002_alter_ottplan_code_skylinkplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ottplan',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10),
        ),
    ]
