# Generated by Django 4.2.19 on 2025-03-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott_subscription', '0003_ottplan_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTTSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('platform_id', models.CharField(max_length=255)),
                ('plan_id', models.CharField(max_length=255)),
                ('subscription_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
