# Generated by Django 4.2.19 on 2025-03-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott_subscription', '0003_ottactivationlog_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ottactivationlog',
            name='subscription_tiers',
            field=models.CharField(default='free', max_length=50),
        ),
    ]
