# Generated by Django 4.2.19 on 2025-03-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott_subscription', '0004_ottsubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTTActivationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=255)),
                ('platform_id', models.CharField(max_length=255)),
                ('plan_id', models.CharField(max_length=255)),
                ('activation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Success', max_length=50)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
