# Generated by Django 4.2.19 on 2025-03-18 07:40

from django.db import migrations, models
import ott_subscription.models


class Migration(migrations.Migration):

    dependencies = [
        ('ott_subscription', '0004_ottactivationlog_subscription_tiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ottactivationlog',
            name='expiration_date',
            field=models.DateTimeField(default=ott_subscription.models.get_expiration_date),
        ),
    ]
