# Generated by Django 4.2.19 on 2025-03-15 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ott_subscription', '0006_ott'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ott',
            name='plan',
        ),
    ]
