# Generated by Django 4.2.19 on 2025-03-21 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ott_subscription', '0007_verificationcode_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
