# Generated by Django 4.2.19 on 2025-03-15 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott_subscription', '0007_remove_ott_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ott',
            name='code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ott',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ott_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])]),
        ),
        migrations.AlterField(
            model_name='ott',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
