# Generated by Django 4.2.19 on 2025-03-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ott_subscription', '0008_ott_code_alter_ott_image_alter_ott_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ott',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
