# Generated by Django 4.2.19 on 2025-03-15 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ott_subscription', '0009_alter_ott_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='ott',
            name='ott_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ott_plans', to='ott_subscription.ottplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ottplan',
            name='otts',
            field=models.ManyToManyField(related_name='ott_plans_associated', to='ott_subscription.ott'),
        ),
    ]
