# Generated by Django 4.2.19 on 2025-02-26 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
